### ISSUE TITLE
Update the value of the field inside an array 

### ISSUE THREAD

**Issue by vivekwolf123** [jossef/action-set-json-field#2]
I have the JSON - 

`{
  "version": "1",
  "myArr": [
    {
      "id": "1"
    }
  ]
}`

I want to change the value of the `id` inside the `sampleArray`. Using the github action, it adds `id` as a new field in the object instead of editing the existing `id`.

Is there any solution for this?

**Comment by jossef** [comment]
sorry for the delayed response. I have 2 suggestions (haven't tested):

Try using the array item index as a sub key `myArr.0.id`

```
- name: Update my-file.json description
  uses: jossef/action-set-json-field@v1
  with:
    file: my-file.json
    field: myArr.0.id
    value: 2
```

Or, you can enable `parse_json: true` and override the entire array

```
- name: Update my-file.json description
  uses: jossef/action-set-json-field@v1
  with:
    file: my-file.json
    field: myArr
    value: [ { "id": "2" } ]
    parse_json: true
```
