### ISSUE TITLE
Trouble with arrays of objects.

### ISSUE THREAD

**Issue by codefriar** [jossef/action-set-json-field#3]
Given the following json:
```json
{
    "packageDirectories": [
        {
            "path": "force-app",
            "default": true,
            "package": "ApexRecipes",
            "versionName": "Spring '21 release",
            "versionNumber": "51.0.0.NEXT"
        }
    ],
    "namespace": "",
    "sfdcLoginUrl": "https://login.salesforce.com",
    "sourceApiVersion": "51.0"
}
```

When I run this action:
```yml
- uses: jossef/action-set-json-field@v1
   with:
     file: sfdx-project.json
     field: packageDirectories[0].versionNumber
     value: ${steps.bumpVersion.output.result}
```

with the field of `packageDirectories[0].versionNumber` the following is *appended* to the file,

` "packageDirectories[0]": {    "versionNumber": "${steps.bumpVersion.output.result}"  }`

It would seem the action isn't aware of how to edit a nested property in an array. Am I doing this wrong, or is this a feature request?
